# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__, np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/luke/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/luke/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/luke/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/luke/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/luke/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/luke/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/luke/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/luke/anaconda3/include']


('1.19.2', None)

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
null_vector.size, null_vector.itemsize

(10, 8)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
reverse_vec = np.arange(30)
reverse_vec[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
non_zeros = np.nonzero([1,2,0,0,4,0])
non_zeros

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random(27).reshape(3,3,3)

array([[[0.71154274, 0.29147016, 0.32821995],
        [0.90905393, 0.53627587, 0.36498028],
        [0.06241185, 0.67333089, 0.83996777]],

       [[0.93321756, 0.47720473, 0.96500226],
        [0.22702898, 0.75261623, 0.85048521],
        [0.93391563, 0.09625935, 0.7297026 ]],

       [[0.92478401, 0.62303267, 0.05039796],
        [0.40363432, 0.12556046, 0.98011891],
        [0.68854484, 0.40906159, 0.12491031]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
ten_by_ten = np.random.random(100).reshape(10,10)
np.min(ten_by_ten), np.max(ten_by_ten)

(0.030774225331881566, 0.995336645181431)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
thiry_vec = np.random.random(30)
np.mean(thiry_vec), thiry_vec

(0.4872293731560063,
 array([0.31593102, 0.28998878, 0.98516538, 0.3428452 , 0.69242229,
        0.6299854 , 0.82729245, 0.27492231, 0.85554174, 0.11532984,
        0.12462543, 0.63859697, 0.47473742, 0.50788691, 0.39218426,
        0.07457072, 0.88660087, 0.94607767, 0.94209035, 0.49316447,
        0.2680565 , 0.23311406, 0.52485845, 0.79652399, 0.1626768 ,
        0.45391941, 0.18888058, 0.05994831, 0.16929564, 0.94964801]))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
ones = np.ones((10,10))
ones[1:-1,1:-1] = 0
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
np.pad(ones, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan

nan

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
np.nan - np.nan

nan

In [22]:
np.nan in set([np.nan])

True

In [23]:
0.3 == 3 * 0.1

False

In [24]:
0.3, 3 * 0.1

(0.3, 0.30000000000000004)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [25]:
np.random.randint(1,5,size=(5,5))

array([[2, 1, 2, 3, 4],
       [3, 2, 3, 1, 1],
       [3, 3, 4, 2, 1],
       [4, 4, 4, 1, 2],
       [1, 3, 2, 2, 2]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
x = np.ones((8,8), dtype=int)
x[1::2,::2] = 0
x[::2,1::2] = 0
x

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [28]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [29]:
np.array([[0,1], [1,0]])

array([[0, 1],
       [1, 0]])

In [30]:
np.tile(np.array([[0,1], [1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [31]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [32]:
x = np.random.random((5,5))
x

array([[0.5443035 , 0.17068893, 0.51392905, 0.09343991, 0.45160267],
       [0.06393169, 0.05871159, 0.81804549, 0.74534414, 0.31815497],
       [0.85486696, 0.60069307, 0.95722983, 0.91142607, 0.3554618 ],
       [0.12337555, 0.62594792, 0.36866469, 0.96724857, 0.73573347],
       [0.16003849, 0.15523134, 0.87983843, 0.81450548, 0.12521268]])

In [33]:
x = (x - x.min())/(x.max() - x.min())
x

array([[0.53447677, 0.12325018, 0.50104451, 0.03822445, 0.43244369],
       [0.00574561, 0.        , 0.83577655, 0.7557563 , 0.28556172],
       [0.87630486, 0.59654311, 0.98897266, 0.93855781, 0.32662425],
       [0.07117373, 0.62434038, 0.34115628, 1.        , 0.74517812],
       [0.11152755, 0.10623646, 0.90379022, 0.83188016, 0.0731958 ]])

In [34]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [36]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
five_by_three = np.arange(15).reshape(5,3)
three_by_two = np.arange(6).reshape(3,2)
five_by_three, three_by_two

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [38]:
three_by_two.T

array([[0, 2, 4],
       [1, 3, 5]])

In [39]:
five_by_three.dot(three_by_two)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [40]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
rand_arr = np.random.randint(1, 11, size=20)
rand_arr

array([ 6,  1,  9,  4,  6,  6,  8,  5,  7,  6,  2,  4,  5,  1,  2,  6,  3,
       10,  5,  9])

In [42]:
rand_arr[(rand_arr>3) & (rand_arr<8)] *= -1
rand_arr

array([-6,  1,  9, -4, -6, -6,  8, -5, -7, -6,  2, -4, -5,  1,  2, -6,  3,
       10, -5,  9])

In [43]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
sum(range(5), -1)

9

In [45]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [50]:
z = np.random.randint(1,5, size=10)
z

array([3, 1, 4, 3, 1, 4, 4, 2, 2, 2])

In [51]:
z**z

array([ 27,   1, 256,  27,   1, 256, 256,   4,   4,   4])

In [58]:
# bit shift operator, in this example: [(2 * 2**3), (2 * 2**1), (2 * 2**4), ...]
2 << z

array([16,  4, 32, 16,  4, 32, 32,  8,  8,  8])

In [64]:
# bit shift operator, in this example: [(2 // 2**3), (2 // 2**1), (2 // 2**4), ...]
z >> 2

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 0])

In [67]:
2 << z >> 2

array([4, 1, 8, 4, 1, 8, 8, 2, 2, 2])

In [68]:
z <- z

array([False, False, False, False, False, False, False, False, False,
       False])

In [70]:
1j*z

array([0.+3.j, 0.+1.j, 0.+4.j, 0.+3.j, 0.+1.j, 0.+4.j, 0.+4.j, 0.+2.j,
       0.+2.j, 0.+2.j])

In [72]:
z/1/1

array([3., 1., 4., 3., 1., 4., 4., 2., 2., 2.])

In [73]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
hint(27)

No hints provided...


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [76]:
np.array(0) / np.array(0)

/home/luke/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [77]:
np.array(0) // np.array(0)

/home/luke/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [78]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [79]:
answer(28)

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [83]:
np.copysign(np.ceil(np.abs(z)), z), np.where(z>0, np.ceil(z), np.floor(z))

(array([3., 1., 4., 3., 1., 4., 4., 2., 2., 2.]),
 array([3., 1., 4., 3., 1., 4., 4., 2., 2., 2.]))

In [84]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [85]:
q = np.random.randint(1, 11, size=20)
w = np.random.randint(1, 11, size=20)

q, w

(array([5, 4, 3, 2, 7, 8, 3, 7, 4, 1, 4, 9, 6, 1, 6, 8, 2, 1, 4, 4]),
 array([ 5,  3,  1,  8,  9,  1, 10, 10, 10,  7,  8,  5,  2,  6, 10,  1,  7,
         1,  9,  8]))

In [87]:
np.intersect1d(q, w)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [88]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [92]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [90]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [93]:
np.seterr(**defaults)

NameError: name 'defaults' is not defined

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [94]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [95]:
answer(32)

np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [97]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

f'Yesterday was {yesterday}, Today is {today}, Tomorrow is {tomorrow},'

'Yesterday was 2021-02-18, Today is 2021-02-19, Tomorrow is 2021-02-20,'

In [96]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [104]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [100]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [126]:
A = np.random.randint(1, 10, 10)
B = np.random.randint(1, 10, 10)
A, B

(array([9, 2, 3, 5, 4, 9, 3, 2, 5, 4]), array([3, 5, 5, 8, 8, 3, 7, 4, 3, 9]))

In [127]:
np.add(A,B, out=B)

array([12,  7,  8, 13, 12, 12, 10,  6,  8, 13])

In [128]:
np.negative(A,out=A)

array([-9, -2, -3, -5, -4, -9, -3, -2, -5, -4])

In [129]:
np.divide(A,2,out=A)

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [ ]:
np.multiply(A,B,out=A)

In [130]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [108]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [134]:
rando = np.random.uniform(0, 10, 10)
rando

array([6.43295932, 0.86350088, 8.37999259, 6.66642428, 9.3841201 ,
       4.508191  , 6.12451112, 2.49372522, 9.28241077, 0.34910178])

In [135]:
rando - rando%1

array([6., 0., 8., 6., 9., 4., 6., 2., 9., 0.])

In [137]:
rando // 1

array([6., 0., 8., 6., 9., 4., 6., 2., 9., 0.])

In [138]:
np.floor(rando)

array([6., 0., 8., 6., 9., 4., 6., 2., 9., 0.])

In [139]:
rando.astype(int)

array([6, 0, 8, 6, 9, 4, 6, 2, 9, 0])

In [141]:
np.trunc(rando)

array([6., 0., 8., 6., 9., 4., 6., 2., 9., 0.])

In [142]:
answer(36)

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [145]:
np.random.randint(0,5,25).reshape(5,5)

array([[2, 0, 3, 2, 4],
       [3, 1, 2, 4, 1],
       [2, 0, 2, 0, 1],
       [2, 1, 0, 4, 3],
       [2, 3, 0, 4, 2]])

In [146]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


In [147]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [149]:
np.fromiter(range(10), dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
hint(38)

hint: np.fromiter


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [150]:
np.random.random(10)

array([0.79719534, 0.77048993, 0.45320314, 0.25102892, 0.87514984,
       0.10080022, 0.27449968, 0.42987063, 0.69156473, 0.50282555])

In [151]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [152]:
sorted(np.random.random(10))

[0.0502747850429881,
 0.10648989629601602,
 0.22567788721866744,
 0.2518251737969408,
 0.2749954452478147,
 0.41027258049907833,
 0.44703160659413665,
 0.6419587759696843,
 0.6697776629061184,
 0.9775551770631256]

In [153]:
answer(40)

Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [155]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.add.reduce(c)

45

In [154]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [157]:
c == Z

/home/luke/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [158]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)